### ISSUE TITLE
Guide on how to contribute?

### ISSUE THREAD

**Issue by tommyettinger** [craftworkgames/Astrid.Framework#1]
1: Will Astrid take pull requests, or is there some other intended method to bring code in? 

2: Documentation seems sparse, but there's no way of telling what will be changed while the in-code docs are being written by a different contributor. Is there some way of allocating work for who-writes-what documentation?

3: Although I'm personally used to using LibGDX by going onto Github and browsing the source when something isn't clear to me, I know most users of that similar library use the wiki. Is the wiki for Astrid intended to fill a similar purpose, that is, the main source for documentation?

4: Is there an IRC channel already? I'm on #astrid on irc.freenode.net ; give me a nick to make the channel's owner and I will see if I can.

**Comment by craftworkgames** [comment]
Hi @tommyettinger 

Welcome to Astrid. You are one of the first contributors to the project outside myself, so most of the questions don't have really good answers yet. If you would like to help me figure out answers

1. Yes, Astrid will take pull requests. I figure we might as well use github the way it's intended. Do you have any other ideas?

2. Right, there's hardly any documentation. I've started a blog but there's not much in it yet.
http://blog.craftworkgames.com/

As for allocating work, currently I'm just managing my task list with a Trello board.  Do you have any thoughts on managing this with multiple people?
https://trello.com/b/egogxXto/astrid-game-framework

3. I think the wiki for LibGDX is very good. It must've taken a long time to put it together though. I would like something similar for Astrid, although, at the moment there's nothing. My plan was to do regular blog posts while building the framework and collect it all together into a wiki in the future.

4. I'll join the channel now and take a look.
